### ISSUE TITLE
Error calling learnCustomEntities()

### ISSUE THREAD

**Issue by kiwikoda** [winkjs/wink-eng-lite-web-model#1]
I'm receiving the following error when calling `learnCustomEntities()` as per the sample code in the documentation.

````
wink-nlp.js:1452 Uncaught SyntaxError: Unexpected token , in JSON at position 3
    at JSON.parse (<anonymous>)
    at Object.importJSON (VM1233 wink-nlp.js:1452)
    at compiler (VM1233 wink-nlp.js:1496)
    at Object.learnCustomEntities (VM1233 wink-nlp.js:1767)
````

Here is a codepen: https://codepen.io/pilotbean/pen/vYXNGLX

**Comment by sanjayaksaxena** [comment]
@kiwikoda we have fixed the issue:

<img width="1678" alt="image" src="https://user-images.githubusercontent.com/29990/100858812-7b296480-34b4-11eb-98d5-97dcfbadb1f3.png">

Thanks once again for your contribution.

**Comment by kiwikoda** [comment]
Brilliant! Thanks, @sanjayaksaxena.
