### ISSUE TITLE
Incorrect PoS tagging for "email"

### ISSUE THREAD

**Issue by boompig** [winkjs/wink-eng-lite-web-model#10]
Hi team, here are some examples where wink improperly tags "email" as a noun (or proper noun) when it is acting as a verb in the sentence.

1. Please email Fred.
2. Email Alice the files
3. Can you please email George? (note that "Can you email George?" is actually parsed correctly, no idea why "please throws the model off)
4. Email me back with the details.

wink-nlp version 1.13.0, wink-eng-lite-web-model version 1.4.3.

**Comment by sanjayaksaxena** [comment]
@boompig Thanks for highlighting. We are currently working on [fine tuning](https://github.com/winkjs/wink-eng-lite-web-model/issues/9#issuecomment-1426111468) the model. We will also try and address the issue highlighted.

**Comment by sanjayaksaxena** [comment]
Hello @boompig 

Have released the updated model (version 1.5.0) on NPM.

Best,
Sanjaya
