### ISSUE TITLE
Uncaught SyntaxError: The requested module 'wink-eng-lite-web-model' does not provide an export named 'default'

### ISSUE THREAD

**Issue by joonaskaustel** [winkjs/wink-eng-lite-web-model#11]
Is it possible to use in Deno somehow?
Getting error 'Uncaught SyntaxError: The requested module 'wink-eng-lite-web-model' does not provide an export named 'default' when importing as import model from https://unpkg.com/wink-eng-lite-web-model@1.5.0/dist/model.js

**Comment by sanjayaksaxena** [comment]
Hello @joonaskaustel 

We have not tested it on deno yet. 

Can you try using it with `https://cdn.skypack.dev/wink-eng-lite-web-model`?

Best,
Sanjaya

**Comment by sanjayaksaxena** [comment]
Hello @joonaskaustel 

We tested it on deno at replit using the following code:
<img width="682" alt="image" src="https://github.com/winkjs/wink-eng-lite-web-model/assets/29990/b1982624-fadb-4f51-be56-20c47519f5e6">

Here is the output:
<img width="537" alt="image" src="https://github.com/winkjs/wink-eng-lite-web-model/assets/29990/bc074789-2bff-43b7-b42d-08ab4db76ce2">

Here is the URL for the same: https://replit.com/@sanjayaksaxena/ParchedDarkkhakiOctagons#index.ts

Best,
Sanjaya
