### ISSUE TITLE
NPM listing for wink-eng-lite-web-model does not link to source repository

### ISSUE THREAD

**Issue by EffectivelyEfficient** [winkjs/wink-eng-lite-web-model#12]
The NPM page for wink-eng-lite-web-model  ( https://www.npmjs.com/package/wink-eng-lite-web-model )
does not link to the source repository. Please link to the repository that is used to build this package.

This means security tools like https://snyk.io/advisor/npm-package/wink-eng-lite-web-model
should no longer have warnings such as "Unable to verify the project's public source code repository."

**Comment by sanjayaksaxena** [comment]
@EffectivelyEfficient thanks for highlighting. We will be adding following to the `package.json` of `wink-eng-lite-web-model`:

```json
"repository": {
    "type": "git",
    "url": "git+https://github.com/winkjs/wink-eng-lite-web-model.git"
  },
```

Best,
Sanjaya

**Comment by sanjayaksaxena** [comment]
@EffectivelyEfficient we have released the updated version on NPM. It might take a day or so to get scanned by `synk`. The repo is now showing up on the NPM page!

Thanks a lot once again for highlighting — we appreciate your contribution.

**Comment by sanjayaksaxena** [comment]
The "Unable to verify the project's public source code repository." has gone away!
