### ISSUE TITLE
Thin spaces (U+2009) are removed from sentences

### ISSUE THREAD

**Issue by dchest** [winkjs/wink-eng-lite-web-model#15]
Example ([using this observable](https://observablehq.com/@winkjs/how-to-split-text-into-sentences)):

```js
{
  const doc = nlp.readDoc("hello world"); 
  doc.sentences()
     .each((e) => e.markup('<tr><td>', '</td></tr>'));
  return html`${'<table><tr><th>Sentences</th>'+doc.out(its.markedUpText)+'</table>'}`;
}
```

This returns: "helloworld".

Note that between _hello_ and _world_ there's U+2009 thin space, not the U+20 space.

**Comment by rachnachakraborty** [comment]
Hi @dchest 

Thank you for highlighting the miss.  

Shall keep you posted here when we fix it. 

Best,
Rachna

**Comment by sanjayaksaxena** [comment]
Released following

1. wink-eng-lite-web-model Version 1.8.0
2. wink-nlp Version 2.3.0

These together now support handling of em/en, third/quarter, thin/hair, medium math spaces & regular/narrow nbsp.

**Comment by dchest** [comment]
Awesome, thanks a lot! I verified that the new versions work with thin spaces in my use case.
