### ISSUE TITLE
Typescript configuration error

### ISSUE THREAD

**Issue by pimpale** [winkjs/wink-eng-lite-web-model#4]
Hi,

Currently I have this error when I try to import wink-eng-lite-web-model:
```
Could not find a declaration file for module 'wink-eng-lite-web-model'
```

This is because I made an error in the previous pull request that I sent. 
In the package.json, there is the line:
```
"types": "types/wink-eng-lite-model.d.ts"
```

This should be changed to:
```
"types": "types/index.d.ts"
```

Thanks,
Govind Pimpale

**Comment by sanjayaksaxena** [comment]
Thanks for highlighting — released a new version with the fix.
